---
- name: add repo to config-manager
  shell: "dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"

- name: install docker
  dnf:
    name:
      - docker-ce-3:25.0.3-1.el9.x86_64
  register: res
  retries: 5
  until: res is success

- name:
  package:
    name: python3-yaml
    state: absent

# pin requests lib due to "urllib3 v2 incompatibility"
# https://github.com/docker/docker-py/issues/3113
# extra_args - to avoid error during install pyyaml on modern ubuntu(22.04)
- name: install wheel
  shell: python3 -m pip install --no-build-isolation wheel
  register: res
  retries: 5
  until: res is success

- name: install python compose
  shell: python3 -m pip install --no-build-isolation 'docker-compose==1.28.6' 'requests<2.29'
  register: res
  retries: 5
  until: res is success

# we mount /etc/timezone from host to containers
# but rocky9 doesn't have such file on host and with some mount it creates folder
# and we have debian based images (like rabbit) which have this file inside
# therefore we get an error during run with mount folder into file
# so let's create file with system content
- name: create file /etc/timezone with system value
  copy:
    content: "{{ ansible_date_time.tz }}"
    dest: "/etc/timezone"
