---
- name: add repo to config-manager
  shell: "dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"

- name: install docker
  dnf:
    name: docker-ce-3:25.0.3-1.el9.x86_64
  register: res
  retries: 5
  until: res is success
