---

- name: run neutron init container
  include_tasks: init_opensdn.yml

- name: config neutron_server container
  include_tasks: config_opensdn.yml

- name: delete containers
  include_tasks: restart_containers.yml
