---
- name: stop contrail analytics_snmp
  docker_service:
    project_src: /etc/contrail/analytics_snmp
    state: absent
  environment:
    DOCKER_CLIENT_TIMEOUT: '120'
    COMPOSE_HTTP_TIMEOUT: '120'
